### ISSUE TITLE
Offsite link might be infinite looping

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/reddit-grab#2]
From reddit thread ID 565435117 base 10:
2703=204 https://bat.bing.com/action/0?ti=4064013&Ver=2  
2704=204 https://bat.bing.com/action/0?ti=4064013&Ver=2  
2705=204 https://bat.bing.com/action/0?ti=4064013&Ver=2

**Comment by marked** [comment]
yeah, these 204's are going to block jobs from finishing as the grab script is not moving on from them.
648=204 https://adserver-us.adtech.advertising.com/
649=204 https://adserver-us.adtech.advertising.com/
650=204 https://adserver-us.adtech.advertising.com/

**Comment by marked** [comment]
2034=204 https://trc.taboola.com/1036135/log/3/unip?en=page_view
2035=204 https://trc.taboola.com/1036135/log/3/unip?en=page_view
...

**Comment by Arkiver2** [comment]
fixed with cf3f6c7af94249ce58ebc4dadcfce9dc111406a5
