### ISSUE TITLE
Too many offsite links

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/reddit-grab#3]
Original post has 3 comments with no embedded offsite links.
Resulting crawl path has a link count in thousands and includes: 
wikipedia, archive.org, and some newspapers.

To reproduce:
git clone https://github.com/ArchiveTeam/reddit-grab.git
cd reddit-grab
wget-lua -U ArchiveTeam -nv --lua-script reddit.lua --load-cookies cookies.txt -o wget.log --no-check-certificate --output-document wget.tmp --truncate-output -e robots=off --rotate-dns --recursive --level=inf --no-parent --page-requisites --timeout 30 --tries inf --domains reddit.com --span-hosts --waitretry 30 --warc-file reddit-posts_326212567-326212567-20190429-072911-$$ --warc-header "operator: Archive Team" --warc-header "reddit-dld-script-version: 20190405.01" --warc-header "reddit-item: posts:326212567-326212567" --warc-header "reddit-post: 5e7v87" https://www.reddit.com/comments/5e7v87 https://old.reddit.com/comments/5e7v87

Output as text file:
[stdout.txt](https://github.com/ArchiveTeam/reddit-grab/files/3127542/stdout.txt)

**Comment by Arkiver2** [comment]
closing as we're not getting offsite links
